-- Query SQL per creare il profilo provider
INSERT INTO provider_profiles (
  user_id,
  business_name,
  vat_number,
  fiscal_code,
  phone,
  website,
  description,
  experience_years,
  team_size,
  street,
  city,
  province,
  postal_code,
  country,
  contact_person_name,
  contact_person_email,
  contact_person_phone,
  specializations,
  service_areas,
  languages,
  rating_average,
  reviews_count,
  verified,
  auto_accept_bookings,
  advance_notice_hours,
  region,
  created_at,
  updated_at
) VALUES (
  'ac97755e-cf3e-40a4-8526-b0e6b9e7c154',
  'Pippo Srl',
  'IT12345678901',
  'CNTPTR95A01H501X',
  '+39 3341001071',
  'https://pippo-srl.it',
  'Pippo Srl è un''azienda specializzata in servizi di sicurezza sul lavoro e formazione HSE. Con anni di esperienza nel settore, offriamo soluzioni complete per la conformità alla normativa di sicurezza.',
  15,
  8,
  'Via Roma 123',
  'Milano',
  'MI',
  '20121',
  'Italy',
  'Patrick Cioni',
  'patrickcioni95@gmail.com',
  '+39 3341001071',
  '{"Sicurezza sul lavoro","Formazione HSE","DVR","Valutazione rischi","Procedure di sicurezza"}',
  '{"Milano","Lombardia","Nord Italia"}',
  '{"Italian","English"}',
  4.8,
  24,
  true,
  false,
  24,
  'Lombardia',
  NOW(),
  NOW()
);