-- BookingHSE Test Users
-- File con utenti di test per testing robusto
-- Nota: Gli UUID devono essere sostituiti con quelli reali dopo la registrazione in Supabase Auth

-- =====================================================
-- UTENTI CLIENT (Aziende che cercano servizi HSE)
-- =====================================================

-- Client 1: Piccola azienda manifatturiera
INSERT INTO client_profiles (
  user_id,
  company_name,
  vat_number,
  fiscal_code,
  company_size,
  industry_sector,
  employees_count,
  phone,
  website,
  legal_street,
  legal_city,
  legal_province,
  legal_postal_code,
  contact_person_name,
  contact_person_role,
  contact_person_email,
  contact_person_phone
) VALUES (
  'c1111111-1111-1111-1111-111111111111',
  'MetalWorks S.r.l.',
  'IT01234567890',
  'MTWRKS80A01H501A',
  'small',
  'Manifatturiero',
  25,
  '+39 02 1111111',
  'https://www.metalworks.it',
  'Via delle Industrie 45',
  'Bergamo',
  'BG',
  '24100',
  'Giovanni Ferretti',
  'Responsabile Sicurezza',
  'g.ferretti@metalworks.it',
  '+39 335 1111111'
);

-- Client 2: Media azienda edile
INSERT INTO client_profiles (
  user_id,
  company_name,
  vat_number,
  fiscal_code,
  company_size,
  industry_sector,
  employees_count,
  phone,
  website,
  legal_street,
  legal_city,
  legal_province,
  legal_postal_code,
  contact_person_name,
  contact_person_role,
  contact_person_email,
  contact_person_phone
) VALUES (
  'c2222222-2222-2222-2222-222222222222',
  'Costruzioni Moderne S.p.A.',
  'IT09876543210',
  'CSTMDN85B15F205B',
  'medium',
  'Edilizia',
  120,
  '+39 011 2222222',
  'https://www.costruzionimoderne.it',
  'Corso Francia 234',
  'Torino',
  'TO',
  '10138',
  'Maria Colombo',
  'HSE Manager',
  'm.colombo@costruzionimoderne.it',
  '+39 347 2222222'
);

-- Client 3: Grande azienda chimica
INSERT INTO client_profiles (
  user_id,
  company_name,
  vat_number,
  fiscal_code,
  company_size,
  industry_sector,
  employees_count,
  phone,
  website,
  legal_street,
  legal_city,
  legal_province,
  legal_postal_code,
  contact_person_name,
  contact_person_role,
  contact_person_email,
  contact_person_phone
) VALUES (
  'c3333333-3333-3333-3333-333333333333',
  'ChemItalia S.p.A.',
  'IT11223344556',
  'CHMITL75C10F205C',
  'large',
  'Chimico',
  850,
  '+39 02 3333333',
  'https://www.chemitalia.it',
  'Via Volta 567',
  'Milano',
  'MI',
  '20131',
  'Roberto Santini',
  'Direttore HSE',
  'r.santini@chemitalia.it',
  '+39 335 3333333'
);

-- Client 4: Micro azienda servizi
INSERT INTO client_profiles (
  user_id,
  company_name,
  vat_number,
  fiscal_code,
  company_size,
  industry_sector,
  employees_count,
  phone,
  legal_street,
  legal_city,
  legal_province,
  legal_postal_code,
  contact_person_name,
  contact_person_role,
  contact_person_email,
  contact_person_phone
) VALUES (
  'c4444444-4444-4444-4444-444444444444',
  'Digital Solutions S.r.l.s.',
  'IT55667788990',
  'DGTLSL90D25H501D',
  'micro',
  'Servizi',
  8,
  '+39 02 4444444',
  'Via Roma 12',
  'Monza',
  'MB',
  '20900',
  'Elena Rossi',
  'Titolare',
  'e.rossi@digitalsolutions.it',
  '+39 348 4444444'
);

-- =====================================================
-- UTENTI PROVIDER (Fornitori di servizi HSE)
-- =====================================================

-- Provider 1: Studio consulenza specializzato in sicurezza
INSERT INTO provider_profiles (
  user_id,
  business_name,
  vat_number,
  fiscal_code,
  professional_order,
  registration_number,
  phone,
  website,
  description,
  experience_years,
  team_size,
  street,
  city,
  province,
  postal_code,
  contact_person_name,
  contact_person_role,
  contact_person_email,
  contact_person_phone,
  specializations,
  service_areas,
  languages,
  rating_average,
  reviews_count,
  verified,
  verification_date,
  auto_accept_bookings,
  advance_notice_hours,
  cancellation_policy
) VALUES (
  'p1111111-1111-1111-1111-111111111111',
  'SafetyFirst Consulting',
  'IT12345678901',
  'SFTFRS80A01H501E',
  'Ordine Ingegneri Milano',
  'ING-MI-11111',
  '+39 02 5555555',
  'https://www.safetyfirst.it',
  'Studio di consulenza specializzato in sicurezza sul lavoro con 20 anni di esperienza. Offriamo valutazioni rischi, formazione e supporto normativo completo.',
  20,
  12,
  'Via Manzoni 123',
  'Milano',
  'MI',
  '20121',
  'Ing. Alessandro Bianchi',
  'Titolare',
  'a.bianchi@safetyfirst.it',
  '+39 335 5555555',
  ARRAY['Valutazione Rischi', 'Formazione Sicurezza', 'D.Lgs 81/08', 'ISO 45001', 'RSPP'],
  ARRAY['Milano', 'Lombardia', 'Piemonte', 'Veneto'],
  ARRAY['Italian', 'English'],
  4.9,
  67,
  true,
  NOW() - INTERVAL '8 months',
  false,
  48,
  'Cancellazione gratuita fino a 48 ore prima. Cancellazioni tardive: 50% del costo.'
);

-- Provider 2: Centro formazione accreditato
INSERT INTO provider_profiles (
  user_id,
  business_name,
  vat_number,
  fiscal_code,
  professional_order,
  registration_number,
  phone,
  website,
  description,
  experience_years,
  team_size,
  street,
  city,
  province,
  postal_code,
  contact_person_name,
  contact_person_role,
  contact_person_email,
  contact_person_phone,
  specializations,
  service_areas,
  languages,
  rating_average,
  reviews_count,
  verified,
  verification_date,
  auto_accept_bookings,
  advance_notice_hours,
  cancellation_policy
) VALUES (
  'p2222222-2222-2222-2222-222222222222',
  'Formazione Sicura Academy',
  'IT98765432109',
  'FRMSIC85B15F205F',
  'Ente Accreditato Regione Lombardia',
  'ACC-LO-22222',
  '+39 02 6666666',
  'https://www.formazionesicura.it',
  'Centro di formazione accreditato specializzato in corsi di sicurezza, antincendio e primo soccorso. Oltre 15 anni di esperienza nella formazione aziendale.',
  15,
  25,
  'Via Garibaldi 456',
  'Brescia',
  'BS',
  '25121',
  'Dott.ssa Francesca Verdi',
  'Direttore Didattico',
  'f.verdi@formazionesicura.it',
  '+39 347 6666666',
  ARRAY['Formazione Sicurezza', 'Antincendio', 'Primo Soccorso', 'Spazi Confinati', 'Lavori in Quota'],
  ARRAY['Brescia', 'Lombardia', 'Veneto', 'Trentino'],
  ARRAY['Italian', 'English', 'German'],
  4.8,
  134,
  true,
  NOW() - INTERVAL '5 months',
  true,
  24,
  'Cancellazione gratuita fino a 24 ore prima. Cancellazioni tardive: 30% del costo.'
);

-- Provider 3: Consulente ambientale freelance
INSERT INTO provider_profiles (
  user_id,
  business_name,
  vat_number,
  fiscal_code,
  professional_order,
  registration_number,
  phone,
  website,
  description,
  experience_years,
  team_size,
  street,
  city,
  province,
  postal_code,
  contact_person_name,
  contact_person_role,
  contact_person_email,
  contact_person_phone,
  specializations,
  service_areas,
  languages,
  rating_average,
  reviews_count,
  verified,
  verification_date,
  auto_accept_bookings,
  advance_notice_hours,
  cancellation_policy
) VALUES (
  'p3333333-3333-3333-3333-333333333333',
  'EcoExpert Consulting',
  'IT33445566778',
  'ECOEXP75C10F205G',
  'Ordine Chimici Lombardia',
  'CHI-LO-33333',
  '+39 02 7777777',
  'https://www.ecoexpert.it',
  'Consulenza ambientale specializzata in VIA, gestione rifiuti e certificazioni ISO 14001. Esperienza decennale in progetti di bonifica e sostenibilità.',
  10,
  3,
  'Via Dante 789',
  'Como',
  'CO',
  '22100',
  'Dott. Marco Neri',
  'Consulente Senior',
  'm.neri@ecoexpert.it',
  '+39 339 7777777',
  ARRAY['Valutazione Impatto Ambientale', 'Gestione Rifiuti', 'ISO 14001', 'Bonifiche', 'Sostenibilità'],
  ARRAY['Como', 'Lombardia', 'Svizzera'],
  ARRAY['Italian', 'English', 'French'],
  4.7,
  28,
  true,
  NOW() - INTERVAL '6 months',
  false,
  72,
  'Cancellazione gratuita fino a 72 ore prima per sopralluoghi. Cancellazioni tardive: 100% del costo.'
);

-- Provider 4: Medico competente
INSERT INTO provider_profiles (
  user_id,
  business_name,
  vat_number,
  fiscal_code,
  professional_order,
  registration_number,
  phone,
  website,
  description,
  experience_years,
  team_size,
  street,
  city,
  province,
  postal_code,
  contact_person_name,
  contact_person_role,
  contact_person_email,
  contact_person_phone,
  specializations,
  service_areas,
  languages,
  rating_average,
  reviews_count,
  verified,
  verification_date,
  auto_accept_bookings,
  advance_notice_hours,
  cancellation_policy
) VALUES (
  'p4444444-4444-4444-4444-444444444444',
  'Studio Medico del Lavoro Dr. Rossi',
  'IT77889900112',
  'RSSMED70D15F205H',
  'Ordine Medici Milano',
  'MED-MI-44444',
  '+39 02 8888888',
  'https://www.studiomedicolavoro.it',
  'Studio medico specializzato in medicina del lavoro. Sorveglianza sanitaria, visite mediche e consulenza per la salute dei lavoratori.',
  25,
  8,
  'Via Montenapoleone 321',
  'Milano',
  'MI',
  '20121',
  'Dott. Giuseppe Rossi',
  'Medico Competente',
  'g.rossi@studiomedicolavoro.it',
  '+39 335 8888888',
  ARRAY['Medicina del Lavoro', 'Sorveglianza Sanitaria', 'Visite Mediche', 'Stress Lavoro-Correlato'],
  ARRAY['Milano', 'Lombardia'],
  ARRAY['Italian', 'English'],
  4.9,
  89,
  true,
  NOW() - INTERVAL '12 months',
  true,
  48,
  'Cancellazione gratuita fino a 48 ore prima. Cancellazioni tardive: 80% del costo per visite mediche.'
);

-- Provider 5: Startup innovativa
INSERT INTO provider_profiles (
  user_id,
  business_name,
  vat_number,
  fiscal_code,
  phone,
  website,
  description,
  experience_years,
  team_size,
  street,
  city,
  province,
  postal_code,
  contact_person_name,
  contact_person_role,
  contact_person_email,
  contact_person_phone,
  specializations,
  service_areas,
  languages,
  rating_average,
  reviews_count,
  verified,
  auto_accept_bookings,
  advance_notice_hours,
  cancellation_policy
) VALUES (
  'p5555555-5555-5555-5555-555555555555',
  'SafeTech Innovation S.r.l.s.',
  'IT99887766554',
  'SFTTECH90E25F205I',
  '+39 02 9999999',
  'https://www.safetech.it',
  'Startup innovativa specializzata in soluzioni digitali per la sicurezza. IoT, AI e realtà aumentata per la prevenzione degli infortuni.',
  3,
  6,
  'Via Tortona 654',
  'Milano',
  'MI',
  '20144',
  'Ing. Sofia Blu',
  'CEO & Founder',
  's.blu@safetech.it',
  '+39 348 9999999',
  ARRAY['Innovazione Digitale', 'IoT Sicurezza', 'Realtà Aumentata', 'AI per HSE'],
  ARRAY['Milano', 'Italia', 'Europa'],
  ARRAY['Italian', 'English', 'Spanish'],
  4.6,
  15,
  false,
  true,
  12,
  'Cancellazione gratuita fino a 12 ore prima. Servizi digitali: cancellazione istantanea.'
);

-- =====================================================
-- NOTA IMPORTANTE
-- =====================================================
-- Gli UUID utilizzati in questo file sono fittizi.
-- Prima di importare questi dati:
-- 1. Creare gli utenti tramite Supabase Auth
-- 2. Sostituire gli UUID con quelli reali
-- 3. Assicurarsi che gli utenti abbiano i ruoli corretti

-- Per creare gli utenti in Supabase Auth, utilizzare:
-- INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, created_at, updated_at)
-- VALUES (...)

-- Poi aggiornare la tabella users:
-- INSERT INTO users (id, email, user_type) VALUES (...)